language: node_js

node_js :
  - stable

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli@1.7.4

script:
    - yarn ci
